products:
  - code:
      B07R4NHLD7

  - code:
      B07T4Q53ZL
    price:
      50

email:
  destinations:
    - mail1

  subject:
    mysubject $title $price $url

  body:
    mybody $title $price $url

sleeping_time:
  10
