products:
  - code: #check price
      B07XJZS6L2
    price:
      55

  - code: #check price
      B07XJZS6L2
    price:
      55

  - code: #check price
      B07XJZS6L2
    price:
      55


  - code: #check available
      B07T3NQBXV

email:
  destinations:
    - mymail@gmail.com

  subject:
    "AmazonTracker : $title"

  body:
    "<html>
    <a href='$url'><H3>$title</H3></a>
    <H3>$price</H3>
    </html>"

notification:
  topic:
    amazon_tracker

  registration_token:
    - device1
    - device2

  title:
    "AmazonTracker"

  body:
    "$price"

sleep:
  3600

iteration_sleep:
  10
